# Server configuration for TestDaemon world

CLUSTERNAMES = [
("base",),
]

WORLDPORT = 2008
ZONESTARTPORT = 2010
PLAYERPASSWORD = "mmo"
MAXPLAYERS = 64
STATICZONES = ["base"]

REBOOT = True
REBOOT_HOUR = 3
REBOOT_MINUTE = 0
